package league.model;

import java.util.Date;

public class Device {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.bb_guid
	 * @mbggenerated
	 */
	private String bbGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.fonts_code
	 * @mbggenerated
	 */
	private String fontsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.id
	 * @return  the value of device.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.id
	 * @param id  the value for device.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.bb_guid
	 * @return  the value of device.bb_guid
	 * @mbggenerated
	 */
	public String getBbGuid() {
		return bbGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.bb_guid
	 * @param bbGuid  the value for device.bb_guid
	 * @mbggenerated
	 */
	public void setBbGuid(String bbGuid) {
		this.bbGuid = bbGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.fonts_code
	 * @return  the value of device.fonts_code
	 * @mbggenerated
	 */
	public String getFontsCode() {
		return fontsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.fonts_code
	 * @param fontsCode  the value for device.fonts_code
	 * @mbggenerated
	 */
	public void setFontsCode(String fontsCode) {
		this.fontsCode = fontsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device.insert_date
	 * @return  the value of device.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device.insert_date
	 * @param insertDate  the value for device.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}