package league.model;

import java.util.Date;

public class Group {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.type
	 * @mbggenerated
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.submit_name
	 * @mbggenerated
	 */
	private String submitName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.submit_password
	 * @mbggenerated
	 */
	private String submitPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.display_group_name
	 * @mbggenerated
	 */
	private String displayGroupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.id
	 * @return  the value of group.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.id
	 * @param id  the value for group.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.type
	 * @return  the value of group.type
	 * @mbggenerated
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.type
	 * @param type  the value for group.type
	 * @mbggenerated
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.submit_name
	 * @return  the value of group.submit_name
	 * @mbggenerated
	 */
	public String getSubmitName() {
		return submitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.submit_name
	 * @param submitName  the value for group.submit_name
	 * @mbggenerated
	 */
	public void setSubmitName(String submitName) {
		this.submitName = submitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.submit_password
	 * @return  the value of group.submit_password
	 * @mbggenerated
	 */
	public String getSubmitPassword() {
		return submitPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.submit_password
	 * @param submitPassword  the value for group.submit_password
	 * @mbggenerated
	 */
	public void setSubmitPassword(String submitPassword) {
		this.submitPassword = submitPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.display_group_name
	 * @return  the value of group.display_group_name
	 * @mbggenerated
	 */
	public String getDisplayGroupName() {
		return displayGroupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.display_group_name
	 * @param displayGroupName  the value for group.display_group_name
	 * @mbggenerated
	 */
	public void setDisplayGroupName(String displayGroupName) {
		this.displayGroupName = displayGroupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group.insert_date
	 * @return  the value of group.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group.insert_date
	 * @param insertDate  the value for group.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}