package league.model;

import java.util.Date;

public class GroupUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.group_id
	 * @mbggenerated
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.login_name
	 * @mbggenerated
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.login_password
	 * @mbggenerated
	 */
	private String loginPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.display_user_name
	 * @mbggenerated
	 */
	private String displayUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_user.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.id
	 * @return  the value of group_user.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.id
	 * @param id  the value for group_user.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.group_id
	 * @return  the value of group_user.group_id
	 * @mbggenerated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.group_id
	 * @param groupId  the value for group_user.group_id
	 * @mbggenerated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.login_name
	 * @return  the value of group_user.login_name
	 * @mbggenerated
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.login_name
	 * @param loginName  the value for group_user.login_name
	 * @mbggenerated
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.login_password
	 * @return  the value of group_user.login_password
	 * @mbggenerated
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.login_password
	 * @param loginPassword  the value for group_user.login_password
	 * @mbggenerated
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.display_user_name
	 * @return  the value of group_user.display_user_name
	 * @mbggenerated
	 */
	public String getDisplayUserName() {
		return displayUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.display_user_name
	 * @param displayUserName  the value for group_user.display_user_name
	 * @mbggenerated
	 */
	public void setDisplayUserName(String displayUserName) {
		this.displayUserName = displayUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_user.insert_date
	 * @return  the value of group_user.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_user.insert_date
	 * @param insertDate  the value for group_user.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}