package league.model;

import java.util.Date;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.pagename
     *
     * @mbggenerated
     */
    private String pagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.insert_date
     *
     * @mbggenerated
     */
    private Date insertDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.login_name
     *
     * @return the value of history.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.login_name
     *
     * @param loginName the value for history.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.pagename
     *
     * @return the value of history.pagename
     *
     * @mbggenerated
     */
    public String getPagename() {
        return pagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.pagename
     *
     * @param pagename the value for history.pagename
     *
     * @mbggenerated
     */
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.message
     *
     * @return the value of history.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.message
     *
     * @param message the value for history.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.ip
     *
     * @return the value of history.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.ip
     *
     * @param ip the value for history.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.insert_date
     *
     * @return the value of history.insert_date
     *
     * @mbggenerated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.insert_date
     *
     * @param insertDate the value for history.insert_date
     *
     * @mbggenerated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }
}