package league.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransDeviceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trans_device
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trans_device
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trans_device
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public TransDeviceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trans_device
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTransactionIdIsNull() {
			addCriterion("transaction_id is null");
			return (Criteria) this;
		}

		public Criteria andTransactionIdIsNotNull() {
			addCriterion("transaction_id is not null");
			return (Criteria) this;
		}

		public Criteria andTransactionIdEqualTo(Integer value) {
			addCriterion("transaction_id =", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdNotEqualTo(Integer value) {
			addCriterion("transaction_id <>", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdGreaterThan(Integer value) {
			addCriterion("transaction_id >", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("transaction_id >=", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdLessThan(Integer value) {
			addCriterion("transaction_id <", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdLessThanOrEqualTo(Integer value) {
			addCriterion("transaction_id <=", value, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdIn(List<Integer> values) {
			addCriterion("transaction_id in", values, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdNotIn(List<Integer> values) {
			addCriterion("transaction_id not in", values, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdBetween(Integer value1, Integer value2) {
			addCriterion("transaction_id between", value1, value2, "transactionId");
			return (Criteria) this;
		}

		public Criteria andTransactionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("transaction_id not between", value1, value2, "transactionId");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIsNull() {
			addCriterion("device_type is null");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIsNotNull() {
			addCriterion("device_type is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeEqualTo(String value) {
			addCriterion("device_type =", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotEqualTo(String value) {
			addCriterion("device_type <>", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeGreaterThan(String value) {
			addCriterion("device_type >", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
			addCriterion("device_type >=", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLessThan(String value) {
			addCriterion("device_type <", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
			addCriterion("device_type <=", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLike(String value) {
			addCriterion("device_type like", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotLike(String value) {
			addCriterion("device_type not like", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIn(List<String> values) {
			addCriterion("device_type in", values, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotIn(List<String> values) {
			addCriterion("device_type not in", values, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeBetween(String value1, String value2) {
			addCriterion("device_type between", value1, value2, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotBetween(String value1, String value2) {
			addCriterion("device_type not between", value1, value2, "deviceType");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageIsNull() {
			addCriterion("browser_language is null");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageIsNotNull() {
			addCriterion("browser_language is not null");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageEqualTo(String value) {
			addCriterion("browser_language =", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageNotEqualTo(String value) {
			addCriterion("browser_language <>", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageGreaterThan(String value) {
			addCriterion("browser_language >", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageGreaterThanOrEqualTo(String value) {
			addCriterion("browser_language >=", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageLessThan(String value) {
			addCriterion("browser_language <", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageLessThanOrEqualTo(String value) {
			addCriterion("browser_language <=", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageLike(String value) {
			addCriterion("browser_language like", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageNotLike(String value) {
			addCriterion("browser_language not like", value, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageIn(List<String> values) {
			addCriterion("browser_language in", values, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageNotIn(List<String> values) {
			addCriterion("browser_language not in", values, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageBetween(String value1, String value2) {
			addCriterion("browser_language between", value1, value2, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserLanguageNotBetween(String value1, String value2) {
			addCriterion("browser_language not between", value1, value2, "browserLanguage");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeIsNull() {
			addCriterion("browser_type is null");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeIsNotNull() {
			addCriterion("browser_type is not null");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeEqualTo(String value) {
			addCriterion("browser_type =", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeNotEqualTo(String value) {
			addCriterion("browser_type <>", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeGreaterThan(String value) {
			addCriterion("browser_type >", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeGreaterThanOrEqualTo(String value) {
			addCriterion("browser_type >=", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeLessThan(String value) {
			addCriterion("browser_type <", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeLessThanOrEqualTo(String value) {
			addCriterion("browser_type <=", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeLike(String value) {
			addCriterion("browser_type like", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeNotLike(String value) {
			addCriterion("browser_type not like", value, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeIn(List<String> values) {
			addCriterion("browser_type in", values, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeNotIn(List<String> values) {
			addCriterion("browser_type not in", values, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeBetween(String value1, String value2) {
			addCriterion("browser_type between", value1, value2, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserTypeNotBetween(String value1, String value2) {
			addCriterion("browser_type not between", value1, value2, "browserType");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionIsNull() {
			addCriterion("browser_version is null");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionIsNotNull() {
			addCriterion("browser_version is not null");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionEqualTo(String value) {
			addCriterion("browser_version =", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionNotEqualTo(String value) {
			addCriterion("browser_version <>", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionGreaterThan(String value) {
			addCriterion("browser_version >", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionGreaterThanOrEqualTo(String value) {
			addCriterion("browser_version >=", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionLessThan(String value) {
			addCriterion("browser_version <", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionLessThanOrEqualTo(String value) {
			addCriterion("browser_version <=", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionLike(String value) {
			addCriterion("browser_version like", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionNotLike(String value) {
			addCriterion("browser_version not like", value, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionIn(List<String> values) {
			addCriterion("browser_version in", values, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionNotIn(List<String> values) {
			addCriterion("browser_version not in", values, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionBetween(String value1, String value2) {
			addCriterion("browser_version between", value1, value2, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andBrowserVersionNotBetween(String value1, String value2) {
			addCriterion("browser_version not between", value1, value2, "browserVersion");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledIsNull() {
			addCriterion("flash_enabled is null");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledIsNotNull() {
			addCriterion("flash_enabled is not null");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledEqualTo(Boolean value) {
			addCriterion("flash_enabled =", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledNotEqualTo(Boolean value) {
			addCriterion("flash_enabled <>", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledGreaterThan(Boolean value) {
			addCriterion("flash_enabled >", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("flash_enabled >=", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledLessThan(Boolean value) {
			addCriterion("flash_enabled <", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("flash_enabled <=", value, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledIn(List<Boolean> values) {
			addCriterion("flash_enabled in", values, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledNotIn(List<Boolean> values) {
			addCriterion("flash_enabled not in", values, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("flash_enabled between", value1, value2, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("flash_enabled not between", value1, value2, "flashEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashVersionIsNull() {
			addCriterion("flash_version is null");
			return (Criteria) this;
		}

		public Criteria andFlashVersionIsNotNull() {
			addCriterion("flash_version is not null");
			return (Criteria) this;
		}

		public Criteria andFlashVersionEqualTo(String value) {
			addCriterion("flash_version =", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionNotEqualTo(String value) {
			addCriterion("flash_version <>", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionGreaterThan(String value) {
			addCriterion("flash_version >", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionGreaterThanOrEqualTo(String value) {
			addCriterion("flash_version >=", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionLessThan(String value) {
			addCriterion("flash_version <", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionLessThanOrEqualTo(String value) {
			addCriterion("flash_version <=", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionLike(String value) {
			addCriterion("flash_version like", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionNotLike(String value) {
			addCriterion("flash_version not like", value, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionIn(List<String> values) {
			addCriterion("flash_version in", values, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionNotIn(List<String> values) {
			addCriterion("flash_version not in", values, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionBetween(String value1, String value2) {
			addCriterion("flash_version between", value1, value2, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashVersionNotBetween(String value1, String value2) {
			addCriterion("flash_version not between", value1, value2, "flashVersion");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledIsNull() {
			addCriterion("flash_storage_enabled is null");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledIsNotNull() {
			addCriterion("flash_storage_enabled is not null");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledEqualTo(Boolean value) {
			addCriterion("flash_storage_enabled =", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledNotEqualTo(Boolean value) {
			addCriterion("flash_storage_enabled <>", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledGreaterThan(Boolean value) {
			addCriterion("flash_storage_enabled >", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("flash_storage_enabled >=", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledLessThan(Boolean value) {
			addCriterion("flash_storage_enabled <", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("flash_storage_enabled <=", value, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledIn(List<Boolean> values) {
			addCriterion("flash_storage_enabled in", values, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledNotIn(List<Boolean> values) {
			addCriterion("flash_storage_enabled not in", values, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("flash_storage_enabled between", value1, value2, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andFlashStorageEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("flash_storage_enabled not between", value1, value2, "flashStorageEnabled");
			return (Criteria) this;
		}

		public Criteria andOperationSystemIsNull() {
			addCriterion("operation_system is null");
			return (Criteria) this;
		}

		public Criteria andOperationSystemIsNotNull() {
			addCriterion("operation_system is not null");
			return (Criteria) this;
		}

		public Criteria andOperationSystemEqualTo(String value) {
			addCriterion("operation_system =", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemNotEqualTo(String value) {
			addCriterion("operation_system <>", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemGreaterThan(String value) {
			addCriterion("operation_system >", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemGreaterThanOrEqualTo(String value) {
			addCriterion("operation_system >=", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemLessThan(String value) {
			addCriterion("operation_system <", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemLessThanOrEqualTo(String value) {
			addCriterion("operation_system <=", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemLike(String value) {
			addCriterion("operation_system like", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemNotLike(String value) {
			addCriterion("operation_system not like", value, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemIn(List<String> values) {
			addCriterion("operation_system in", values, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemNotIn(List<String> values) {
			addCriterion("operation_system not in", values, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemBetween(String value1, String value2) {
			addCriterion("operation_system between", value1, value2, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andOperationSystemNotBetween(String value1, String value2) {
			addCriterion("operation_system not between", value1, value2, "operationSystem");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionIsNull() {
			addCriterion("screen_resolution is null");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionIsNotNull() {
			addCriterion("screen_resolution is not null");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionEqualTo(String value) {
			addCriterion("screen_resolution =", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionNotEqualTo(String value) {
			addCriterion("screen_resolution <>", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionGreaterThan(String value) {
			addCriterion("screen_resolution >", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionGreaterThanOrEqualTo(String value) {
			addCriterion("screen_resolution >=", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionLessThan(String value) {
			addCriterion("screen_resolution <", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionLessThanOrEqualTo(String value) {
			addCriterion("screen_resolution <=", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionLike(String value) {
			addCriterion("screen_resolution like", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionNotLike(String value) {
			addCriterion("screen_resolution not like", value, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionIn(List<String> values) {
			addCriterion("screen_resolution in", values, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionNotIn(List<String> values) {
			addCriterion("screen_resolution not in", values, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionBetween(String value1, String value2) {
			addCriterion("screen_resolution between", value1, value2, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andScreenResolutionNotBetween(String value1, String value2) {
			addCriterion("screen_resolution not between", value1, value2, "screenResolution");
			return (Criteria) this;
		}

		public Criteria andTimeZoneIsNull() {
			addCriterion("time_zone is null");
			return (Criteria) this;
		}

		public Criteria andTimeZoneIsNotNull() {
			addCriterion("time_zone is not null");
			return (Criteria) this;
		}

		public Criteria andTimeZoneEqualTo(String value) {
			addCriterion("time_zone =", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneNotEqualTo(String value) {
			addCriterion("time_zone <>", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneGreaterThan(String value) {
			addCriterion("time_zone >", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneGreaterThanOrEqualTo(String value) {
			addCriterion("time_zone >=", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneLessThan(String value) {
			addCriterion("time_zone <", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneLessThanOrEqualTo(String value) {
			addCriterion("time_zone <=", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneLike(String value) {
			addCriterion("time_zone like", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneNotLike(String value) {
			addCriterion("time_zone not like", value, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneIn(List<String> values) {
			addCriterion("time_zone in", values, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneNotIn(List<String> values) {
			addCriterion("time_zone not in", values, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneBetween(String value1, String value2) {
			addCriterion("time_zone between", value1, value2, "timeZone");
			return (Criteria) this;
		}

		public Criteria andTimeZoneNotBetween(String value1, String value2) {
			addCriterion("time_zone not between", value1, value2, "timeZone");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNull() {
			addCriterion("insert_date is null");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNotNull() {
			addCriterion("insert_date is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDateEqualTo(Date value) {
			addCriterion("insert_date =", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotEqualTo(Date value) {
			addCriterion("insert_date <>", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThan(Date value) {
			addCriterion("insert_date >", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_date >=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThan(Date value) {
			addCriterion("insert_date <", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThanOrEqualTo(Date value) {
			addCriterion("insert_date <=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateIn(List<Date> values) {
			addCriterion("insert_date in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotIn(List<Date> values) {
			addCriterion("insert_date not in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateBetween(Date value1, Date value2) {
			addCriterion("insert_date between", value1, value2, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotBetween(Date value1, Date value2) {
			addCriterion("insert_date not between", value1, value2, "insertDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trans_device
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trans_device
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}