package league.model;

import java.util.Date;

public class TransDevice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.transaction_id
	 * @mbggenerated
	 */
	private Integer transactionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.device_type
	 * @mbggenerated
	 */
	private String deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.browser_language
	 * @mbggenerated
	 */
	private String browserLanguage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.browser_type
	 * @mbggenerated
	 */
	private String browserType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.browser_version
	 * @mbggenerated
	 */
	private String browserVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.flash_enabled
	 * @mbggenerated
	 */
	private Boolean flashEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.flash_version
	 * @mbggenerated
	 */
	private String flashVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.flash_storage_enabled
	 * @mbggenerated
	 */
	private Boolean flashStorageEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.operation_system
	 * @mbggenerated
	 */
	private String operationSystem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.screen_resolution
	 * @mbggenerated
	 */
	private String screenResolution;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.time_zone
	 * @mbggenerated
	 */
	private String timeZone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_device.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.id
	 * @return  the value of trans_device.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.id
	 * @param id  the value for trans_device.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.transaction_id
	 * @return  the value of trans_device.transaction_id
	 * @mbggenerated
	 */
	public Integer getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.transaction_id
	 * @param transactionId  the value for trans_device.transaction_id
	 * @mbggenerated
	 */
	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.device_type
	 * @return  the value of trans_device.device_type
	 * @mbggenerated
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.device_type
	 * @param deviceType  the value for trans_device.device_type
	 * @mbggenerated
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.browser_language
	 * @return  the value of trans_device.browser_language
	 * @mbggenerated
	 */
	public String getBrowserLanguage() {
		return browserLanguage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.browser_language
	 * @param browserLanguage  the value for trans_device.browser_language
	 * @mbggenerated
	 */
	public void setBrowserLanguage(String browserLanguage) {
		this.browserLanguage = browserLanguage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.browser_type
	 * @return  the value of trans_device.browser_type
	 * @mbggenerated
	 */
	public String getBrowserType() {
		return browserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.browser_type
	 * @param browserType  the value for trans_device.browser_type
	 * @mbggenerated
	 */
	public void setBrowserType(String browserType) {
		this.browserType = browserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.browser_version
	 * @return  the value of trans_device.browser_version
	 * @mbggenerated
	 */
	public String getBrowserVersion() {
		return browserVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.browser_version
	 * @param browserVersion  the value for trans_device.browser_version
	 * @mbggenerated
	 */
	public void setBrowserVersion(String browserVersion) {
		this.browserVersion = browserVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.flash_enabled
	 * @return  the value of trans_device.flash_enabled
	 * @mbggenerated
	 */
	public Boolean getFlashEnabled() {
		return flashEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.flash_enabled
	 * @param flashEnabled  the value for trans_device.flash_enabled
	 * @mbggenerated
	 */
	public void setFlashEnabled(Boolean flashEnabled) {
		this.flashEnabled = flashEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.flash_version
	 * @return  the value of trans_device.flash_version
	 * @mbggenerated
	 */
	public String getFlashVersion() {
		return flashVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.flash_version
	 * @param flashVersion  the value for trans_device.flash_version
	 * @mbggenerated
	 */
	public void setFlashVersion(String flashVersion) {
		this.flashVersion = flashVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.flash_storage_enabled
	 * @return  the value of trans_device.flash_storage_enabled
	 * @mbggenerated
	 */
	public Boolean getFlashStorageEnabled() {
		return flashStorageEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.flash_storage_enabled
	 * @param flashStorageEnabled  the value for trans_device.flash_storage_enabled
	 * @mbggenerated
	 */
	public void setFlashStorageEnabled(Boolean flashStorageEnabled) {
		this.flashStorageEnabled = flashStorageEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.operation_system
	 * @return  the value of trans_device.operation_system
	 * @mbggenerated
	 */
	public String getOperationSystem() {
		return operationSystem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.operation_system
	 * @param operationSystem  the value for trans_device.operation_system
	 * @mbggenerated
	 */
	public void setOperationSystem(String operationSystem) {
		this.operationSystem = operationSystem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.screen_resolution
	 * @return  the value of trans_device.screen_resolution
	 * @mbggenerated
	 */
	public String getScreenResolution() {
		return screenResolution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.screen_resolution
	 * @param screenResolution  the value for trans_device.screen_resolution
	 * @mbggenerated
	 */
	public void setScreenResolution(String screenResolution) {
		this.screenResolution = screenResolution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.time_zone
	 * @return  the value of trans_device.time_zone
	 * @mbggenerated
	 */
	public String getTimeZone() {
		return timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.time_zone
	 * @param timeZone  the value for trans_device.time_zone
	 * @mbggenerated
	 */
	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_device.insert_date
	 * @return  the value of trans_device.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_device.insert_date
	 * @param insertDate  the value for trans_device.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}