package league.model;

import java.util.Date;

public class TransLocation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.transaction_id
	 * @mbggenerated
	 */
	private Integer transactionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.ip
	 * @mbggenerated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.country_id
	 * @mbggenerated
	 */
	private String countryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.city
	 * @mbggenerated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.isp
	 * @mbggenerated
	 */
	private String isp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_location.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.id
	 * @return  the value of trans_location.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.id
	 * @param id  the value for trans_location.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.transaction_id
	 * @return  the value of trans_location.transaction_id
	 * @mbggenerated
	 */
	public Integer getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.transaction_id
	 * @param transactionId  the value for trans_location.transaction_id
	 * @mbggenerated
	 */
	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.ip
	 * @return  the value of trans_location.ip
	 * @mbggenerated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.ip
	 * @param ip  the value for trans_location.ip
	 * @mbggenerated
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.country_id
	 * @return  the value of trans_location.country_id
	 * @mbggenerated
	 */
	public String getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.country_id
	 * @param countryId  the value for trans_location.country_id
	 * @mbggenerated
	 */
	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.city
	 * @return  the value of trans_location.city
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.city
	 * @param city  the value for trans_location.city
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.isp
	 * @return  the value of trans_location.isp
	 * @mbggenerated
	 */
	public String getIsp() {
		return isp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.isp
	 * @param isp  the value for trans_location.isp
	 * @mbggenerated
	 */
	public void setIsp(String isp) {
		this.isp = isp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_location.insert_date
	 * @return  the value of trans_location.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_location.insert_date
	 * @param insertDate  the value for trans_location.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}