package league.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transaction
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transaction
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table transaction
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public TransactionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table transaction
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Integer value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Integer value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Integer value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Integer value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Integer> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Integer> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNull() {
			addCriterion("device_id is null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNotNull() {
			addCriterion("device_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdEqualTo(Integer value) {
			addCriterion("device_id =", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotEqualTo(Integer value) {
			addCriterion("device_id <>", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThan(Integer value) {
			addCriterion("device_id >", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("device_id >=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThan(Integer value) {
			addCriterion("device_id <", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
			addCriterion("device_id <=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIn(List<Integer> values) {
			addCriterion("device_id in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotIn(List<Integer> values) {
			addCriterion("device_id not in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
			addCriterion("device_id between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("device_id not between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNull() {
			addCriterion("account_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNotNull() {
			addCriterion("account_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNameEqualTo(String value) {
			addCriterion("account_name =", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotEqualTo(String value) {
			addCriterion("account_name <>", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThan(String value) {
			addCriterion("account_name >", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
			addCriterion("account_name >=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThan(String value) {
			addCriterion("account_name <", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThanOrEqualTo(String value) {
			addCriterion("account_name <=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLike(String value) {
			addCriterion("account_name like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotLike(String value) {
			addCriterion("account_name not like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIn(List<String> values) {
			addCriterion("account_name in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotIn(List<String> values) {
			addCriterion("account_name not in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameBetween(String value1, String value2) {
			addCriterion("account_name between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotBetween(String value1, String value2) {
			addCriterion("account_name not between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andResultIsNull() {
			addCriterion("result is null");
			return (Criteria) this;
		}

		public Criteria andResultIsNotNull() {
			addCriterion("result is not null");
			return (Criteria) this;
		}

		public Criteria andResultEqualTo(Short value) {
			addCriterion("result =", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotEqualTo(Short value) {
			addCriterion("result <>", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThan(Short value) {
			addCriterion("result >", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThanOrEqualTo(Short value) {
			addCriterion("result >=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThan(Short value) {
			addCriterion("result <", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThanOrEqualTo(Short value) {
			addCriterion("result <=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultIn(List<Short> values) {
			addCriterion("result in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotIn(List<Short> values) {
			addCriterion("result not in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultBetween(Short value1, Short value2) {
			addCriterion("result between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotBetween(Short value1, Short value2) {
			addCriterion("result not between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdIsNull() {
			addCriterion("rule_set_id is null");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdIsNotNull() {
			addCriterion("rule_set_id is not null");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdEqualTo(Integer value) {
			addCriterion("rule_set_id =", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdNotEqualTo(Integer value) {
			addCriterion("rule_set_id <>", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdGreaterThan(Integer value) {
			addCriterion("rule_set_id >", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("rule_set_id >=", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdLessThan(Integer value) {
			addCriterion("rule_set_id <", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdLessThanOrEqualTo(Integer value) {
			addCriterion("rule_set_id <=", value, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdIn(List<Integer> values) {
			addCriterion("rule_set_id in", values, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdNotIn(List<Integer> values) {
			addCriterion("rule_set_id not in", values, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdBetween(Integer value1, Integer value2) {
			addCriterion("rule_set_id between", value1, value2, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleSetIdNotBetween(Integer value1, Integer value2) {
			addCriterion("rule_set_id not between", value1, value2, "ruleSetId");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultIsNull() {
			addCriterion("rule_check_result is null");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultIsNotNull() {
			addCriterion("rule_check_result is not null");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultEqualTo(String value) {
			addCriterion("rule_check_result =", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultNotEqualTo(String value) {
			addCriterion("rule_check_result <>", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultGreaterThan(String value) {
			addCriterion("rule_check_result >", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultGreaterThanOrEqualTo(String value) {
			addCriterion("rule_check_result >=", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultLessThan(String value) {
			addCriterion("rule_check_result <", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultLessThanOrEqualTo(String value) {
			addCriterion("rule_check_result <=", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultLike(String value) {
			addCriterion("rule_check_result like", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultNotLike(String value) {
			addCriterion("rule_check_result not like", value, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultIn(List<String> values) {
			addCriterion("rule_check_result in", values, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultNotIn(List<String> values) {
			addCriterion("rule_check_result not in", values, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultBetween(String value1, String value2) {
			addCriterion("rule_check_result between", value1, value2, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andRuleCheckResultNotBetween(String value1, String value2) {
			addCriterion("rule_check_result not between", value1, value2, "ruleCheckResult");
			return (Criteria) this;
		}

		public Criteria andFnsCodeIsNull() {
			addCriterion("fns_code is null");
			return (Criteria) this;
		}

		public Criteria andFnsCodeIsNotNull() {
			addCriterion("fns_code is not null");
			return (Criteria) this;
		}

		public Criteria andFnsCodeEqualTo(String value) {
			addCriterion("fns_code =", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeNotEqualTo(String value) {
			addCriterion("fns_code <>", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeGreaterThan(String value) {
			addCriterion("fns_code >", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeGreaterThanOrEqualTo(String value) {
			addCriterion("fns_code >=", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeLessThan(String value) {
			addCriterion("fns_code <", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeLessThanOrEqualTo(String value) {
			addCriterion("fns_code <=", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeLike(String value) {
			addCriterion("fns_code like", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeNotLike(String value) {
			addCriterion("fns_code not like", value, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeIn(List<String> values) {
			addCriterion("fns_code in", values, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeNotIn(List<String> values) {
			addCriterion("fns_code not in", values, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeBetween(String value1, String value2) {
			addCriterion("fns_code between", value1, value2, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andFnsCodeNotBetween(String value1, String value2) {
			addCriterion("fns_code not between", value1, value2, "fnsCode");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceIsNull() {
			addCriterion("is_new_device is null");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceIsNotNull() {
			addCriterion("is_new_device is not null");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceEqualTo(Boolean value) {
			addCriterion("is_new_device =", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceNotEqualTo(Boolean value) {
			addCriterion("is_new_device <>", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceGreaterThan(Boolean value) {
			addCriterion("is_new_device >", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_new_device >=", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceLessThan(Boolean value) {
			addCriterion("is_new_device <", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceLessThanOrEqualTo(Boolean value) {
			addCriterion("is_new_device <=", value, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceIn(List<Boolean> values) {
			addCriterion("is_new_device in", values, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceNotIn(List<Boolean> values) {
			addCriterion("is_new_device not in", values, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceBetween(Boolean value1, Boolean value2) {
			addCriterion("is_new_device between", value1, value2, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andIsNewDeviceNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_new_device not between", value1, value2, "isNewDevice");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNull() {
			addCriterion("insert_date is null");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNotNull() {
			addCriterion("insert_date is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDateEqualTo(Date value) {
			addCriterion("insert_date =", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotEqualTo(Date value) {
			addCriterion("insert_date <>", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThan(Date value) {
			addCriterion("insert_date >", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_date >=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThan(Date value) {
			addCriterion("insert_date <", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThanOrEqualTo(Date value) {
			addCriterion("insert_date <=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateIn(List<Date> values) {
			addCriterion("insert_date in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotIn(List<Date> values) {
			addCriterion("insert_date not in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateBetween(Date value1, Date value2) {
			addCriterion("insert_date between", value1, value2, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotBetween(Date value1, Date value2) {
			addCriterion("insert_date not between", value1, value2, "insertDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table transaction
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transaction
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}