package league.model;

import java.util.Date;

public class Transaction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.group_id
	 * @mbggenerated
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.device_id
	 * @mbggenerated
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.account_name
	 * @mbggenerated
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.result
	 * @mbggenerated
	 */
	private Short result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.rule_set_id
	 * @mbggenerated
	 */
	private Integer ruleSetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.rule_check_result
	 * @mbggenerated
	 */
	private String ruleCheckResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.fns_code
	 * @mbggenerated
	 */
	private String fnsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.is_new_device
	 * @mbggenerated
	 */
	private Boolean isNewDevice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transaction.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.id
	 * @return  the value of transaction.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.id
	 * @param id  the value for transaction.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.group_id
	 * @return  the value of transaction.group_id
	 * @mbggenerated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.group_id
	 * @param groupId  the value for transaction.group_id
	 * @mbggenerated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.device_id
	 * @return  the value of transaction.device_id
	 * @mbggenerated
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.device_id
	 * @param deviceId  the value for transaction.device_id
	 * @mbggenerated
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.account_name
	 * @return  the value of transaction.account_name
	 * @mbggenerated
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.account_name
	 * @param accountName  the value for transaction.account_name
	 * @mbggenerated
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.result
	 * @return  the value of transaction.result
	 * @mbggenerated
	 */
	public Short getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.result
	 * @param result  the value for transaction.result
	 * @mbggenerated
	 */
	public void setResult(Short result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.rule_set_id
	 * @return  the value of transaction.rule_set_id
	 * @mbggenerated
	 */
	public Integer getRuleSetId() {
		return ruleSetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.rule_set_id
	 * @param ruleSetId  the value for transaction.rule_set_id
	 * @mbggenerated
	 */
	public void setRuleSetId(Integer ruleSetId) {
		this.ruleSetId = ruleSetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.rule_check_result
	 * @return  the value of transaction.rule_check_result
	 * @mbggenerated
	 */
	public String getRuleCheckResult() {
		return ruleCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.rule_check_result
	 * @param ruleCheckResult  the value for transaction.rule_check_result
	 * @mbggenerated
	 */
	public void setRuleCheckResult(String ruleCheckResult) {
		this.ruleCheckResult = ruleCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.fns_code
	 * @return  the value of transaction.fns_code
	 * @mbggenerated
	 */
	public String getFnsCode() {
		return fnsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.fns_code
	 * @param fnsCode  the value for transaction.fns_code
	 * @mbggenerated
	 */
	public void setFnsCode(String fnsCode) {
		this.fnsCode = fnsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.is_new_device
	 * @return  the value of transaction.is_new_device
	 * @mbggenerated
	 */
	public Boolean getIsNewDevice() {
		return isNewDevice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.is_new_device
	 * @param isNewDevice  the value for transaction.is_new_device
	 * @mbggenerated
	 */
	public void setIsNewDevice(Boolean isNewDevice) {
		this.isNewDevice = isNewDevice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transaction.insert_date
	 * @return  the value of transaction.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transaction.insert_date
	 * @param insertDate  the value for transaction.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}