package league.model;

import java.util.Date;

public class UserT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.user_name
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.user_fullname
	 * @mbggenerated
	 */
	private String userFullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.age
	 * @mbggenerated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.insert_date
	 * @mbggenerated
	 */
	private Date insertDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.id
	 * @return  the value of user_t.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.id
	 * @param id  the value for user_t.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.user_name
	 * @return  the value of user_t.user_name
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.user_name
	 * @param userName  the value for user_t.user_name
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.user_fullname
	 * @return  the value of user_t.user_fullname
	 * @mbggenerated
	 */
	public String getUserFullname() {
		return userFullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.user_fullname
	 * @param userFullname  the value for user_t.user_fullname
	 * @mbggenerated
	 */
	public void setUserFullname(String userFullname) {
		this.userFullname = userFullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.password
	 * @return  the value of user_t.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.password
	 * @param password  the value for user_t.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.age
	 * @return  the value of user_t.age
	 * @mbggenerated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.age
	 * @param age  the value for user_t.age
	 * @mbggenerated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.address
	 * @return  the value of user_t.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.address
	 * @param address  the value for user_t.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.insert_date
	 * @return  the value of user_t.insert_date
	 * @mbggenerated
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.insert_date
	 * @param insertDate  the value for user_t.insert_date
	 * @mbggenerated
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
}