package league.dao;

import java.util.List;
import league.model.Transaction;
import league.model.TransactionExample;
import org.apache.ibatis.annotations.Param;

public interface TransactionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int countByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int deleteByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int insert(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int insertSelective(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	List<Transaction> selectByExample(TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	Transaction selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Transaction record, @Param("example") TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Transaction record, @Param("example") TransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Transaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table transaction
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Transaction record);
}